leverage platform extensions
react-native-community/react-native-drawer-layout-polyfill pull request #1
Opened 2017-03-15 20:26 UTC by chirag04

leverage platform extension files so that they are not unnecessarily included in the bundle.

2017-03-15 20:26 UTC, chirag04 commented
cc @DanielMSchmidt @satya164

2017-03-15 20:34 UTC, satya164 commented on src/index.android.js
> +import { DrawerLayoutAndroid } from 'react-native';
This should work

`export { DrawerLayoutAndroid as default } from 'react-native';`

2017-03-15 20:34 UTC, satya164 commented on src/index.ios.js
> +import DrawerLayout from 'react-native-drawer-layout';
This should work (not sure)

`export from 'react-native-drawer-layout';`

or

`export { default as default } from 'react-native-drawer-layout';`

2017-03-15 20:43 UTC, chirag04 commented on src/index.ios.js
> +import DrawerLayout from 'react-native-drawer-layout';
`babel-plugin-transform-export-extensions` is not available by default in RN.

2017-03-15 20:48 UTC, satya164 commented on src/index.ios.js
> +import DrawerLayout from 'react-native-drawer-layout';
`export { default as default } from 'react-native-drawer-layout';` should require any plugin

2017-03-15 21:16 UTC, chirag04 commented on src/index.ios.js
> +import DrawerLayout from 'react-native-drawer-layout';
I just double checked. that does not work. i would leave it as is.

2017-03-15 22:23 UTC, DanielMSchmidt requested changes
We had it like this before but this would be a problem for windows code. I think leaving it as it is would be the option with the least amount of duplicate code, right?

2017-03-15 23:23 UTC, chirag04 commented
I can add a .windows.js file if that's supported

2017-03-16 00:13 UTC, satya164 commented
Why not `index.js` and `index.android.js` though?

2017-03-16 00:14 UTC, satya164 commented
Also feels weird to mix common js export and es6 import. Any reason it's not ES6 export?

2017-03-16 00:18 UTC, satya164 commented on src/index.ios.js
> +import DrawerLayout from 'react-native-drawer-layout';
What happens? This is a valid export syntax in ES2015 and works as expected for me with just `es2015` preset.

2017-03-16 00:36 UTC, chirag04 commented
@satya164 I didn't realize packager prioritizes `.extension.js` over `.js`? About the import, yeah. I rushed this little bit. I can fix those.

2017-03-16 00:51 UTC, satya164 commented
Yes, the packager will look for `index.{ios|android}.js`, `index.native.js` and `index.js`.

2017-03-16 06:49 UTC, DanielMSchmidt commented
I would be in favour of a `index.android.js` and a `index.js` file, this sounds nice. Also we should switch to ES6 exports and also change the readme to state that for people using the commonjs syntax. Thank you so much for your help @chirag04 @satya164 !

2017-03-16 06:49 UTC, DanielMSchmidt commented on src/index.android.js
> +import { DrawerLayoutAndroid } from 'react-native';
Wow, this would be so neat!

2017-03-16 13:48 UTC, chirag04 commented
ok. addressed the feedback

2017-03-16 13:49 UTC, DanielMSchmidt approved these changes
Thank you for this PR, I will test it out later today and ship it afterwards

2017-03-16 13:51 UTC, chirag04 commented
@DanielMSchmidt let's merge after this is merged and bumped: https://github.com/react-native-community/react-native-drawer-layout/pull/17

I can bump the dependency for drawer-layout after that one is merged.

2017-03-16 14:08 UTC, DanielMSchmidt commented
Yeah, good idea!

2017-03-17 08:13 UTC, merged